### ISSUE TITLE
Missing entry for 'language'

### ISSUE THREAD

**Issue by Hollicsh** [cr4ckp0t/ElvUI_MinimapButton#1]
Hey !

2x AceLocale-3.0-6-ElvUI: ElvUI_MinimapButton: Missing entry for 'enUS'
[string "@ElvUI_Libraries/Core/Ace3/AceLocale-3.0-6/AceLocale-3.0.lua"]:131: in function `NewLocale'
[string "@ElvUI_MinimapButton/Locales/enUS.lua"]:9: in main chunk

2x AceLocale-3.0-6-ElvUI: ElvUI_MinimapButton: Missing entry for 'defaultLocale'
[string "@ElvUI_Libraries/Core/Ace3/AceLocale-3.0-6/AceLocale-3.0.lua"]:139: in function `NewLocale'
[string "@ElvUI_MinimapButton/Locales/enUS.lua"]:9: in main chunk

And more .. More ... More ....

![Screenshot_2](https://user-images.githubusercontent.com/54585769/219377698-e110af6b-0d93-4be0-8d2a-25ca00e82fbc.png)

**Comment by cr4ckp0t** [comment]
Okay, it should be fixed now in version 1.1.2.
